export const events = {

    ON:'SimonOn',
    OFF:'machineOFF',
    LEVELUP:'levelUp',
    GAMEOVER:'gameOver',
    NOTECLICKED:'noteClicked',
    LOADPAGE:'loadPage',
    WRONGINPUT:'wrongInput',
    RESET:'reset',
    USERRESET:'userReset',
    SEQUENCESTARTING:'sequenceStarting',
    SOUNDPRESSED: 'soundPressed',
    PLAYPRESSED: 'playPressed',
    POWERPRESSED:'powerPressed',
    YELLOWPRESSED:'yellowPressed',
    REDPRESSED:'redPressed',
    BLUEPRESSED:'bluePressed',
    GREENPRESSED:'greenPressed',
    YELLOWRELEASED:'yellowReleased',
    REDRELEASED:'redReleased',
    BLUERELEASED:'blueReleased',
    GREENRELEASED:'greenReleased',

}